-- package.path = ".\\?.lua;" .. package.path

--- 名字生成函数模块
-- 根据性别，随机生成名字
-- @class module
-- @author Jason Tou sosoayaen@gmail.com
-- @copyright Jason Tou
module("name", package.seeall)

-- 姓氏
local firstMaleNameTbl =
{
	{en = 'Ward', cn = '沃德'},
	{en = 'Washington', cn = '华盛顿'},
	{en = 'Constance', cn = '康斯坦斯'},
	{en = 'Hawthorne', cn = '霍索恩'},
	{en = 'Alick', cn = '阿利克 '},
	{en = 'Whit', cn = '惠特'},
	{en = 'Reynolds', cn = '雷诺兹'},
	{en = 'Adolph', cn = '阿道夫'},
	{en = 'Hewlett', cn = '休利特'},
	{en = 'Montgomery', cn = '蒙哥马利'},
	{en = 'Dillon', cn = '狄龙'},
	{en = 'Bacon', cn = '培根'},
	{en = 'Jonathan', cn = '乔纳森'},
	{en = 'Wright', cn = '赖特'},
	{en = 'Partridge', cn = '帕特里奇'},
	{en = 'Ellis', cn = '艾利斯'},
	{en = 'Blake', cn = '布莱克'},
	{en = 'Brewster', cn = '布鲁斯特'},
	{en = 'Oscar', cn = '奥斯卡'},
	{en = 'Matthew', cn = '马修'},
	{en = 'Wagner', cn = '瓦格纳'},
	{en = 'Margery', cn = '马杰里'},
	{en = 'Marcus', cn = '马库斯'},
	{en = 'Tours', cn = '图尔斯'},
	{en = 'Emma', cn = '埃玛'},
	{en = 'Boyle', cn = '波伊尔'},
	{en = 'Arabella', cn = '阿拉贝拉'},
	{en = 'Charley', cn = '查利'},
	{en = 'Lamb', cn = '拉姆'},
	{en = 'Harte', cn = '哈特'},
	{en = 'Thomas', cn = '托马斯'},
	{en = 'Occam', cn = '奥卡姆'},
	{en = 'Hamilton', cn = '汉森尔顿'},
	{en = 'Julius', cn = '朱利叶斯'},
	{en = 'Burke', cn = '伯克'},
	{en = 'Strachey', cn = '斯特雷奇'},
	{en = 'Lawson', cn = '劳森'},
	{en = 'Carmen', cn = '卡门'},
	{en = 'Byron', cn = '拜伦'},
	{en = 'Raphael', cn = '拉菲尔'},
	{en = 'Barton', cn = '巴顿'},
	{en = 'Nell', cn = '内尔'},
	{en = 'Victor', cn = '维克托'},
	{en = 'Adams', cn = '亚当斯'},
	{en = 'Mat(h)ilda', cn = '马蒂尔达'},
	{en = 'Houston', cn = '休斯敦'},
	{en = 'Law', cn = '劳'},
	{en = 'Eden', cn = '艾登'},
	{en = 'Moore', cn = '穆尔'},
	{en = 'Harrod', cn = '哈罗德'},
	{en = 'Herty', cn = '赫蒂'},
	{en = 'Turner', cn = '特纳'},
	{en = 'Ted', cn = '特德'},
	{en = 'Quiller', cn = '奎勒'},
	{en = 'George', cn = '乔治'},
	{en = 'Jeremy', cn = '杰里米'},
	{en = 'Yeates', cn = '耶茨'},
	{en = 'Motley', cn = '莫特利'},
	{en = 'Carnegie', cn = '卡内基'},
	{en = 'Henry', cn = '亨利'},
	{en = 'Harvey', cn = '哈维'},
	{en = 'Irving', cn = '欧文'},
	{en = 'Francis', cn = '弗朗西斯'},
	{en = 'Wat', cn = '沃特'},
	{en = 'Leigh', cn = '利'},
	{en = 'Bertha', cn = '伯莎'},	
	{en = 'Birrell', cn = '比勒尔'},
	{en = 'Windsor', cn = '温莎'},
	{en = 'Shakespeare', cn = '莎士比亚'},
	{en = 'Beard', cn = '比尔德'},
	{en = 'Leacock', cn = '利科克'},
	{en = 'Hearst', cn = '赫斯特'},
	{en = 'Cissie', cn = '锡西 '},
	{en = 'Harold', cn = '哈罗德'},
	{en = 'Black', cn = '布莱克'},
	{en = 'Bloomer', cn = '布卢默'},
	{en = 'Frank', cn = '弗兰克'},
	{en = 'Winifred', cn = '威尼弗雷德'},
	{en = 'Ellen', cn = '埃伦'},
	{en = 'Clare', cn = '克莱尔 '},
	{en = 'Harrington', cn = '哈林顿'},
	{en = 'Veblen', cn = '维布伦'},
	{en = 'Buck', cn = '巴克'},
	{en = 'Douglas(s)', cn = '道格拉斯'},
	{en = 'Amelia', cn = '阿米利亚'},
	{en = 'Vogt', cn = '沃格特'},
	{en = 'Felix', cn = '费利克斯'},
	{en = 'Barney', cn = '巴尼 '},
	{en = 'Wood', cn = '伍德'},
	{en = 'Chapman', cn = '查普曼'},
	{en = 'Geordie', cn = '乔迪'},
	{en = 'Waters', cn = '沃特斯'},
	{en = 'Thompson', cn = '汤普森'},
	{en = 'Edith', cn = '伊迪丝'},
	{en = 'Evans', cn = '埃文思'},
	{en = 'Moll', cn = '莫尔'},
	{en = 'Hudson', cn = '赫德森'},
	{en = 'Oliver', cn = '奥利弗'},
	{en = 'Hood', cn = '胡德'},
	{en = 'Christian', cn = '克里琴斯'},
	{en = 'Garcia', cn = '加西亚'},
	{en = 'Eipstein', cn = '艾泼斯坦'},
	{en = 'Robert', cn = '罗伯特'},
	{en = 'Nelly', cn = '内利'},
	{en = 'Conan', cn = '科南'},
	{en = 'Augustine', cn = '奥古斯丁'},
	{en = 'Laurie', cn = '劳里'},
	{en = 'Daniel', cn = '丹尼尔'},
	{en = 'Smith', cn = '史密斯'},
	{en = 'Eugen', cn = '尤金'},
	{en = 'Maltz', cn = '马尔兹'},
	{en = 'Wallis', cn = '沃利斯'},
	{en = 'Tomlinson', cn = '汤姆林森'},
	{en = 'Edison', cn = '爱迪生'},
	{en = 'Forster', cn = '福斯特'},
	{en = 'Saul', cn = '索尔'},
	{en = 'Maud', cn = '莫德'},
	{en = 'Philemon', cn = '菲利蒙'},
	{en = 'DeQuincey', cn = '德.昆西'},
	{en = 'Ricardo', cn = '理嘉图'},
	{en = 'Moulton', cn = '莫尔顿'},
	{en = 'Electra', cn = '伊利克特拉'},
	{en = 'Onions', cn = '奥尼恩斯'},
	{en = 'Madge', cn = '马奇'},
	{en = 'Watt', cn = '瓦特'},
	{en = 'Marcellus', cn = '马塞勒斯'},
	{en = 'Nehemiah', cn = '尼赫迈亚'},
	{en = 'Parker', cn = '帕克'},
	{en = 'Chamberlain', cn = '张伯伦'},
	{en = 'Mond', cn = '蒙德'},
	{en = 'Darwin', cn = '达尔文'},
	{en = 'Fred', cn = '弗雷德'},
	{en = 'Gray', cn = '格雷'},
	{en = 'Bennett', cn = '贝内特'},
	{en = 'Dutt', cn = '杜德'},
	{en = 'Eddie', cn = '埃迪'},
	{en = 'Carroll', cn = '卡罗尔'},
	{en = 'Jerome', cn = '杰罗姆'},
	{en = 'Nancy', cn = '南希'},
	{en = 'Dupont', cn = '杜邦'},
	{en = 'Abe', cn = '阿贝'},
	{en = 'Coverdale', cn = '科弗代尔'},
	{en = 'Owen', cn = '欧文'},
	{en = 'Daniell', cn = '丹尼尔'},
	{en = 'Stone', cn = '斯通'},
	{en = 'Lynch', cn = '林奇'},
	{en = 'Doherty', cn = '道尔蒂'},
	{en = 'Bessie', cn = '贝西 '},
	{en = 'Hume', cn = '休姆'},
	{en = 'Malthus', cn = '马尔萨斯'},
	{en = 'Peggy', cn = '佩吉'},
	{en = 'Gibson', cn = '吉布森'},
	{en = 'Max', cn = '马克斯'},
	{en = 'Warner', cn = '沃纳'},
	{en = 'Reade', cn = '里德'},
	{en = 'Spenser', cn = '斯潘塞'},
	{en = 'Flynn', cn = '弗林'},
	{en = 'Romeo', cn = '罗密欧'},
}

local firstFemaleNameTbl = 
{
	{en = 'Mary', cn = '玛丽'},
	{en = 'Anastasia', cn = '阿娜丝塔'},
	{en = 'Pamela', cn = '帕梅拉'},
	{en = 'Sophia', cn = '苏菲亚'},
	{en = 'Modesty', cn = '摩黛丝提'},
	{en = 'Vicky', cn = '维基'},
	{en = 'Coral', cn = '卡洛儿'},
	{en = 'Lillian', cn = '丽莲'},
	{en = 'Aurora', cn = '奥劳拉'},
	{en = 'Maria', cn = '玛丽亚'},
	{en = 'Mamie', cn = '梅蜜'},
	{en = 'Thera', cn = '席拉'},
	{en = 'Xenia', cn = '芝妮雅'},
	{en = 'Alva', cn = '阿尔娃'},
	{en = 'Tess', cn = '泰丝'},
	{en = 'Edwina', cn = '艾德文娜'},
	{en = 'Marguerite', cn = '玛格丽特'},
	{en = 'Verna', cn = '维娜'},
	{en = 'Gustave', cn = '葛佳丝塔芙'},
	{en = 'Tiffany', cn = '蒂法尼'},
	{en = 'Arabela', cn = '爱勒贝拉'},
	{en = 'Sandy', cn = '仙蒂'},
	{en = 'Pag', cn = '佩格'},
	{en = 'Mabel', cn = '玛佩尔'},
	{en = 'Celeste', cn = '西莱斯特'},
	{en = 'Natalie', cn = '纳塔利'},
	{en = 'Michaelia', cn = '蜜雪莉雅'},
	{en = 'Spring', cn = '丝柏凌'},
	{en = 'Elma', cn = '艾尔玛'},
	{en = 'Flora', cn = '弗罗拉'},
	{en = 'Kelly', cn = '凯莉'},
	{en = 'Vera', cn = '维拉'},
	{en = 'Nydia', cn = '妮蒂亚'},
	{en = 'Marian', cn = '玛丽安'},
	{en = 'April', cn = '艾谱莉'},
	{en = 'Joyce', cn = '乔伊斯'},
	{en = 'Margaret', cn = '玛格丽特'},
	{en = 'Jodie', cn = '乔蒂'},
	{en = 'Cathy', cn = '凯丝'},
	{en = 'Ina', cn = '艾娜'},
	{en = 'Ula', cn = '优拉'},
	{en = 'Maureen', cn = '穆琳'},
	{en = 'Rita', cn = '莉达'},
	{en = 'Sandra', cn = '珊多拉'},
	{en = 'Katherine', cn = '凯瑟琳'},
	{en = 'Ruby', cn = '露比'},
	{en = 'Renee', cn = '蕾妮'},
	{en = 'Rae', cn = '瑞伊'},
	{en = 'Murray', cn = '玛瑞'},
	{en = 'Cornelia', cn = '可妮莉雅'},
	{en = 'Lindsay', cn = '林赛'},
	{en = 'Miranda', cn = '米兰达'},
	{en = 'Nancy', cn = '南希'},
	{en = 'Polly', cn = '珀莉'},
	{en = 'Wallis', cn = '华莉丝'},
	{en = 'Griselda', cn = '葛莉谢尔达'},
	{en = 'Daphne', cn = '黛芙妮'},
	{en = 'Delia', cn = '迪丽雅'},
	{en = 'Winifred', cn = '威尼弗雷德'},
	{en = 'Bella', cn = '贝拉'},
	{en = 'Phoenix', cn = '菲妮克丝'},
	{en = 'Arlene', cn = '艾琳娜'},
	{en = 'Myrna', cn = '蜜尔娜'},
	{en = 'Eileen', cn = '艾琳'},
	{en = 'Heather', cn = '赫瑟尔'},
	{en = 'Diana', cn = '黛安娜'},
	{en = 'Belinda', cn = '贝琳达'},
	{en = 'Tracy', cn = '翠西'},
	{en = 'Beulah', cn = '比尤莱'},
	{en = 'Hedy', cn = '赫蒂'},
	{en = 'May', cn = '梅'},
	{en = 'Dorothy', cn = '桃乐斯'},
	{en = 'Odelia', cn = '奥蒂莉亚'},
	{en = 'Caroline', cn = '卡罗琳'},
	{en = 'Gladys', cn = '格拉迪斯'},
	{en = 'Lorraine', cn = '洛兰'},
	{en = 'Sheila', cn = '希拉'},
	{en = 'Ruth', cn = '鲁思'},
	{en = 'Lynn', cn = '琳'},
	{en = 'Xanthe', cn = '桑席'},
	{en = 'Iris', cn = '爱莉丝'},
	{en = 'Lauren', cn = '罗伦'},
	{en = 'Nelly', cn = '内丽'},
	{en = 'Genevieve', cn = '珍妮芙'},
	{en = 'Pearl', cn = '佩儿'},
	{en = 'Roxanne', cn = '罗克珊'},
	{en = 'Agatha', cn = '阿加莎'},
	{en = 'Isabel', cn = '伊莎蓓尔'},
	{en = 'Natividad', cn = '娜提雅维达'},
	{en = 'Yvonne', cn = '伊芳'},
	{en = 'Marjorie', cn = '玛乔丽'},
	{en = 'Bertha', cn = '柏莎'},
	{en = 'Quintina', cn = '昆蒂娜'},
	{en = 'Mavis', cn = '梅薇思'},
	{en = 'Olivia', cn = '奥丽薇亚'},
	{en = 'Adelaide', cn = '爱得莱德'},
	{en = 'Joa', cn = '琼'},
	{en = 'Gwendolyn', cn = '关德琳'},
	{en = 'Constance', cn = '康斯坦丝'},
	{en = 'Yvette', cn = '依耶芙特'},
	{en = 'Carol', cn = '卡萝'},
	{en = 'Elvira', cn = '埃尔韦拉'},
	{en = 'Cherry', cn = '绮莉'},
	{en = 'Amelia', cn = '阿蜜莉雅'},
	{en = 'Nicola', cn = '妮可拉'},
	{en = 'Ivy', cn = '艾薇'},
	{en = 'Liz', cn = '莉斯'},
	{en = 'Dora', cn = '多拉'},
	{en = 'Truda', cn = '杜达'},
	{en = 'Shirley', cn = '雪莉'},
	{en = 'Karen', cn = '凯伦'},
	{en = 'Norma', cn = '诺玛'},
	{en = 'Fanny', cn = '梵妮'},
	{en = 'Michelle', cn = '米歇尔'},
	{en = 'Meredith', cn = '玛莉提丝'},
	{en = 'Grace', cn = '葛瑞丝'},
	{en = 'Laura', cn = '罗拉'},
	{en = 'Yetta', cn = '依耶塔'},
	{en = 'Dana', cn = '黛娜'},
	{en = 'Sabrina', cn = '莎柏琳娜'},
	{en = 'Poppy', cn = '波比'},
	{en = 'Laurel', cn = '罗瑞尔'},
	{en = 'Lilith', cn = '李莉斯'},
	{en = 'Afra', cn = '阿芙拉'},
	{en = 'Miriam', cn = '蜜莉恩'},
	{en = 'Elva', cn = '艾娃'},
	{en = 'Sibyl', cn = '希贝儿'},
	{en = 'Suzanne', cn = '苏珊'},
	{en = 'Bblythe', cn = '布莱兹'},
	{en = 'Hilda', cn = '希尔达'},
	{en = 'Honey', cn = '汉妮'},
	{en = 'Frederica', cn = '菲蕾德翠卡'},
	{en = 'Astrid', cn = '艾丝翠得'},
	{en = 'Lesley', cn = '雷思丽'},
	{en = 'Marina', cn = '马丽娜'},
	{en = 'Jacqueline', cn = '杰奎琳'},
	{en = 'Nicole', cn = '妮可'},
	{en = 'Betty', cn = '贝蒂'},
	{en = 'Bess', cn = '贝丝'},
	{en = 'Beatrice', cn = '碧翠丝'},
	{en = 'Sarah', cn = '赛拉'},
	{en = 'Hedda', cn = '赫达'},
	{en = 'Charlotte', cn = '夏洛特'},
	{en = 'Eden', cn = '伊甸'},
	{en = 'Tabitha', cn = '泰贝莎'},
	{en = 'Kitty', cn = '吉蒂'},
	{en = 'Teresa', cn = '特莉萨'},
	{en = 'Dominic', cn = '多明尼卡'},
	{en = 'Eve', cn = '伊芙'},
	{en = 'Anna', cn = '安娜'},
	{en = 'Leona', cn = '利昂娜'},
	{en = 'Gemma', cn = '姬玛'},
	{en = 'Roberta', cn = '洛蓓塔'},
	{en = 'Minnie', cn = '明妮'},
	{en = 'Petty', cn = '佩蒂'},
	{en = 'Maggie', cn = '玛吉'},
	{en = 'Juliet', cn = '朱丽叶'},
	{en = 'Shelley', cn = '雪莱'},
	{en = 'Emily', cn = '艾米丽'},
	{en = 'Jenny', cn = '珍妮'},
	{en = 'Anne', cn = '安妮'},
	{en = 'Bess', cn = '贝丝 '},
	{en = 'Caroline', cn = '卡罗琳'},
}

local lastNameTbl =
{
	{en = 'bell', cn = '贝尔'},
	{en = 'garcia', cn = '加西亚'},
	{en = 'edward', cn = '爱德华'},
	{en = 'hall', cn = '霍尔'},
	{en = 'gerard', cn = '杰拉德'},
	{en = 'leslie', cn = '莱斯利'},
	{en = 'campbell', cn = '坎贝尔'},
	{en = 'lester', cn = '莱斯特'},
	{en = 'joyce', cn = '乔伊斯'},
	{en = 'keith', cn = '基思'},
	{en = 'taylor', cn = '泰勒'},
	{en = 'dale', cn = '达勒'},
	{en = 'percy', cn = '珀西'},
	{en = 'scott', cn = '斯科特'},
	{en = 'baker', cn = '贝克'},
	{en = 'hill', cn = '希尔'},
	{en = 'evelyn', cn = '伊夫林'},
	{en = 'anderson', cn = '安德森'},
	{en = 'james', cn = '詹姆斯'},
	{en = 'warren', cn = '瓦伦'},
	{en = 'peters', cn = '彼得斯'},
	{en = 'quick', cn = '奎克'},
	{en = 'rodney', cn = '罗德尼'},
	{en = 'green', cn = '格林'},
	{en = 'leonard', cn = '伦纳德'},
	{en = 'carter', cn = '卡特'},
	{en = 'raphael', cn = '拉斐尔'},
	{en = 'fergus', cn = '弗格斯'},
	{en = 'oliver', cn = '奥利弗'},
	{en = 'smith', cn = '斯密斯'},
	{en = 'duncan', cn = '邓肯'},
	{en = 'charles', cn = '查尔斯'},
	{en = 'clive', cn = '克莱夫'},
	{en = 'cook', cn = '库克'},
	{en = 'shelley', cn = '雪莱'},
	{en = 'clark', cn = '克拉克'},
	{en = 'rupert', cn = '鲁珀特'},
	{en = 'eddy', cn = '艾迪'},
	{en = 'david', cn = '戴维德'},
	{en = 'giles', cn = '贾尔斯'},
	{en = 'owen', cn = '欧文'},
	{en = 'tuener', cn = '特纳'},
	{en = 'lewis', cn = '刘易斯'},
	{en = 'murphy', cn = '墨菲'},
	{en = 'harris', cn = '哈里斯'},
	{en = 'adams', cn = '亚当斯'},
	{en = 'walker', cn = '沃克'},
	{en = 'williams', cn = '威廉姆斯'},
	{en = 'kirk', cn = '柯克'},
	{en = 'christian', cn = '克里斯蒂安'},
	{en = 'cecil', cn = '塞西尔'},
	{en = 'arnold', cn = '阿诺德'},
	{en = 'griffin', cn = '格里芬'},
	{en = 'jackson', cn = '杰克逊'},
	{en = 'gary', cn = '加里'},
	{en = 'nelson', cn = '纳尔森'},
	{en = 'Martin', cn = '马丁'},
	{en = 'Eisenhower', cn = '艾森豪威尔'},
	{en = 'Jordan', cn = '乔丹'},
	{en = 'Burne-Jones', cn = '伯恩-琼斯'},
}

-- 前缀，绰号
local prefix = 
{
}

-- 过滤数据并输出新的表格数据（lua源码格式）
local nameDuplicatedfilter = function(nameTbl)
	local at = {}
	print(string.format("local %s = \n{", nameTbl))
	table.foreachi(lastNameTbl, function(_, t)
		if not at[t.en] then
			at[t.en] = true
			print(string.format("\t{en = '%s', cn = '%s'},", t.en, t.cn))
		end
	end)
	print(string.format("}"))
end


require 'util'

-- 当前支持的文字语言
local languageTbl = 
{
	['cn'] = true,	-- 中文简体
	['en'] = true	-- 英文
}
--- 根据性别生成名字
function GenerateNameByGender(gender, language)
	local name = ""
	
	local tempFirstNameTbl = nil
	-- 根据性别得到名字
	if gender == 'male' then
		tempFirstNameTbl = firstMaleNameTbl
	elseif gender == 'female' then
		tempFirstNameTbl = firstFemaleNameTbl
	end
	
	-- 得到姓氏
	local lastNameIdx = util.genRand(#lastNameTbl, 1)
	local lastName = lastNameTbl[lastNameIdx]
	
	local firstNameIdx = util.genRand(#tempFirstNameTbl, 1)
	local firstName = tempFirstNameTbl[firstNameIdx]
	
	-- 根据语言选项设定
	if languageTbl[language] then
		name = firstName[language] .. ' ' .. lastName[language]
	else
		-- 默认中文简体
		name = firstName.cn .. ' ' .. lastName.cn
	end
	
--	print(name)
	return name
end
